// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALjiVfxDJPEKb068-Z4mh_cyVVoY5JE6Q',
    appId: '1:347442297903:web:1920c766fc28ad0b01dada',
    messagingSenderId: '347442297903',
    projectId: 'financne-tracker',
    authDomain: 'financne-tracker.firebaseapp.com',
    storageBucket: 'financne-tracker.firebasestorage.app',
    measurementId: 'G-BQXVYBNYWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDom8DG4kp8YrkrDYKgNqt5RQjEI0o7MAc',
    appId: '1:347442297903:android:fedfd9b737742a5801dada',
    messagingSenderId: '347442297903',
    projectId: 'financne-tracker',
    storageBucket: 'financne-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKF3eKMteNRTeL2tscGhFcj90TjZUqp6w',
    appId: '1:347442297903:ios:53df346de4a09d6401dada',
    messagingSenderId: '347442297903',
    projectId: 'financne-tracker',
    storageBucket: 'financne-tracker.firebasestorage.app',
    androidClientId: '347442297903-05tp3c4q690a7sccobjjhjhrq5dtnkvi.apps.googleusercontent.com',
    iosClientId: '347442297903-jm463esqi9s8fv3ed2ukg77okmes92jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKF3eKMteNRTeL2tscGhFcj90TjZUqp6w',
    appId: '1:347442297903:ios:53df346de4a09d6401dada',
    messagingSenderId: '347442297903',
    projectId: 'financne-tracker',
    storageBucket: 'financne-tracker.firebasestorage.app',
    androidClientId: '347442297903-05tp3c4q690a7sccobjjhjhrq5dtnkvi.apps.googleusercontent.com',
    iosClientId: '347442297903-jm463esqi9s8fv3ed2ukg77okmes92jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALjiVfxDJPEKb068-Z4mh_cyVVoY5JE6Q',
    appId: '1:347442297903:web:1aa45132b5b14aed01dada',
    messagingSenderId: '347442297903',
    projectId: 'financne-tracker',
    authDomain: 'financne-tracker.firebaseapp.com',
    storageBucket: 'financne-tracker.firebasestorage.app',
    measurementId: 'G-ZWQ3BVYM71',
  );

}